[package.image]
versions = ["0.25"]
use_default_features = true
features = []

[package.nalgebra]
versions = []
use_default_features = true
features = []

[package.opencv]
versions = ["0.94"]
use_default_features = false
features = ["calib3d"]

[package.ndarray]
versions = []
use_default_features = true
features = []

[package.tch]
versions = []
use_default_features = true
features = []

[package.imageproc]
versions = ["0.25"]
use_default_features = true
features = []
